on: push

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          xcodebuild test \
            -project SlowPredicateExpectationExample.xcodeproj \
            -scheme SlowPredicateExpectationExample \
            -destination 'platform=iOS Simulator,name=iPhone 13 Pro' -sdk iphonesimulator # | xcbeautify
